#!/bin/sh

# WARNING: this script only works with maven, please install it in your env

BASEDIR=$(dirname "$0")

rm -rf $BASEDIR/../target
mkdir -p $BASEDIR/../target

echo 'Building Hadoop MapReduce version...'
(
  cd $BASEDIR/../hadoop-mr/
  ../tool/apache-maven/bin/mvn assembly:assembly
  cp target/pagerank-0.0.1-SNAPSHOT-jar-with-dependencies.jar ../target/hadoop.jar
)

echo 'Building Apache Spark version...'
(
  cd $BASEDIR/../spark
  sbt package
  cp target/scala-2.10/pagerank_2.10-1.0.jar ../target/spark.jar
)
