#!/bin/sh

BASEDIR=$(dirname "$0")

hdfs dfs -rm -f -r tmp
hdfs dfs -rm -f -r $2

hdfs dfs -mkdir -p tmp
hdfs dfs -mkdir -p tmp/titles

hadoop jar $BASEDIR/../target/hadoop.jar cp2016.pagerank.parse.App $1 tmp/init
hadoop jar $BASEDIR/../target/hadoop.jar cp2016.pagerank.filter.App tmp/init tmp/previous
hadoop jar $BASEDIR/../target/hadoop.jar cp2016.pagerank.sink.App tmp/previous tmp/dummy

hadoop jar $BASEDIR/../target/hadoop.jar cp2016.pagerank.iterate.App tmp/previous tmp/current

hdfs dfs -cat tmp/sinkNodeScore
